define(["../logic/FormDemo"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6"
        },
        root:["page2_header","pagecontent","checklist","radiolist"],
        components:{
            checklist:{
              type:"checklist",
              primaryKey:"id"
            },
            radiolist:{
              type:"radiolist",
              primaryKey:"id",
              labelKey:"label"
            },
            page2_header:{
                type:"view",
                root:["backIcon","right_icon","header_title"],
                style:{
                    height:"44px",
                    borderBottom:"1px solid #e2e8ed",
                    backgroundColor:"#fff",
                    justifyContent:"center",
                    alignItems:"center"
                }
            },
            backIcon:{
              type:"icon",
              text:"返回",
              style:{
                position: "absolute",
                left: "0px",
                color: "rgb(0, 147, 255)",
                top: "7px",
                width: "50px",
                height: "30px",
              },
              textStyle: {
                fontSize: "15px"
              }
            },
            header_title:{
                type:"text",
                text:"表单",
                style:{
                  fontSize:14
                }
            },
            right_icon:{
                type:"icon",
                font:"icomoon_e90e",
                style:{
                    position:"absolute",
                    right:"10px",
                    color:"rgb(0, 147, 255)",
                    top:"6px",
                    width:"30px",
                    height:"30px",
                },
                iconStyle:{
                    fontSize:"20px"
                }
            },
            pagecontent:{
              type:"view",
              style:{
                overflowY:"auto",
                flex:1,
                backgroundColor:"#f3f4f5"
              },
              root:["proj_title_wrapper","proj_title_inp","proj_desc_label","proj_desc_textarea","proj_open_wrapper","startTimeWrapper","endTimeWrapper","importantWrpper","sourceWrapper","addressWrapper","submitbtn"]
            },

            splitline:{
              type:"view",
              style:{
                position:"absolute",
                left:8,
                bottom:0,
                right:0,
                borderTop:"1px solid rgb(245, 245, 245)"
              }
            },
            splitline2:{
              type:"view",
              style:{
                position:"absolute",
                left:8,
                bottom:0,
                right:0,
                borderTop:"1px solid rgb(245, 245, 245)"
              }
            },

            startTimeWrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"stretch",
                marginTop:8,
                height:40,
                backgroundColor:"#fff",
                paddingLeft:8,
                paddingRight:8
              },
              root:["starttime_label","starttime","splitline"]
            },
            starttime_label:{
              type:"text",
              text:"开始时间",
              style:{
                fontSize:13,
                color:"#999",
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            starttime:{
              type:"icon",
              textPos:"left",
              style:{flex:1,justifyContent:"flex-end"},
              textStyle:{
                flex:1,
                fontSize:12,
                alignItems:"flex-end"
              },
              text:"请选择",
              font:"icomoon_e913"
            },

            importantWrpper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"stretch",
                height:40,
                backgroundColor:"#fff",
                marginTop:8,
                paddingLeft:8,
                paddingRight:8
              },
              root:["importantLabel","importantvalue","splitline2"]
            },
            importantLabel:{
              type:"text",
              text:"重要程度",
              style:{
                fontSize:13,
                color:"#999",
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            importantvalue:{
              type:"icon",
              textPos:"left",
              style:{flex:1,justifyContent:"flex-end"},
              text:"请选择",
              textStyle:{
                flex:1,
                fontSize:12,
                alignItems:"flex-end"
              },
              font:"icomoon_e913"
            },



            addressWrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"stretch",
                height:40,
                backgroundColor:"#fff",
                marginTop:8,
                paddingLeft:8,
                paddingRight:8
              },
              root:["addressLabel","addressval"]
            },
            addressLabel:{
              type:"text",
              text:"地址",
              style:{
                fontSize:13,
                color:"#999",
              }
            },
            addressval:{
              type:"icon",
              textPos:"left",
              style:{flex:1,justifyContent:"flex-end"},
              text:"请选择",
              textStyle:{
                flex:1,
                fontSize:12,
                alignItems:"flex-end"
              },
              font:"icomoon_e913"
            },


            sourceWrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"stretch",
                height:40,
                backgroundColor:"#fff",
                paddingLeft:8,
                paddingRight:8
              },
              root:["sourceLabel","sourcevalue"]
            },
            sourceLabel:{
              type:"text",
              text:"配合资源",
              style:{
                fontSize:13,
                color:"#999",
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            sourcevalue:{
              type:"icon",
              textPos:"left",
              style:{flex:1,justifyContent:"flex-end"},
              text:"请选择",
              textStyle:{
                flex:1,
                fontSize:12,
                alignItems:"flex-end"
              },
              font:"icomoon_e913"
            },



            endTimeWrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"stretch",
                height:40,
                backgroundColor:"#fff",
                paddingLeft:8,
                paddingRight:8
              },
              root:["endtime_label","endtime"]
            },
            endtime_label:{
              type:"text",
              text:"结束时间",
              style:{
                fontSize:13,
                color:"#999",
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            endtime:{
              type:"icon",
              textPos:"left",
              style:{flex:1,justifyContent:"flex-end"},
              text:"请选择",
              textStyle:{
                flex:1,
                fontSize:12,
                alignItems:"flex-end"
              },
              font:"icomoon_e913"
            },

            proj_open_wrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"center",
                marginTop:8,
                height:36,
                paddingLeft:8,
                paddingRight:8,
                backgroundColor:"#fff"
              },
              root:["proj_open_title","proj_open_switch"]
            },
            proj_open_switch:{
              type:"switch",
              value:false
            },
            proj_open_title:{
              type:"text",
              text:"公开",
              style:{
                fontSize:13,
                color:"#999",
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            submitbtn:{
              type:"button",
              mode:"2",
              style:{
                margin:"10px auto",
                width:300,
                height:35,
                marginBottom:30
              },
              title:"提交"
            },
            proj_title_inp:{
              type:"input",
              style:{
                height:40,
                backgroundColor:"#fff",
                fontSize:13,
                paddingLeft:7
              },
              placeholder:"请输入项目名称(20个字以内)"
            },
            proj_desc_label:{
              type:"text",
              text:"项目描述",
              style:{
                fontSize:12,
                color:"#999",
                padding:"4px 8px"
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            proj_title_wrapper:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                alignItems:"center",
                padding:"4px 8px"
              },
              root:["proj_title","proj_title_warn"]
            },
            proj_desc_textarea:{
              type:"textarea",
              placeholder:"请输入项目描述",
              style:{
                height:90,
                paddingLeft:7,
                fontSize:13,
                paddingTop:5,
              },
            },
            proj_title:{
              type:"text",
              text:"项目名称",
              style:{
                fontSize:12,
                color:"#999"
              },
              preText:"*",
              preTextStyle:{
                color:"red",
                marginRight:2,
                fontSize:16,
                paddingTop:4
              }
            },
            proj_title_warn:{
              type:"text",
              text:"超过20个字",
              style:{
                fontSize:12,
                color:"#ff4e5b"
              }
            }
        }
    };
});
