define(["../logic/layout"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        root:["page_header","content_wrapper"],
        components:{
            page_header:{
                type:"view",
                root:["backIcon","header_title"],
                style:{
                    height:"44px",
                    borderBottom:"1px solid #e2e8ed",
                    backgroundColor:"#fff",
                    justifyContent:"center",
                    alignItems:"center"
                }
            },
            backIcon:{
              type:"icon",
              text:"返回",
              style:{
                position: "absolute",
                left: "0px",
                color: "rgb(0, 147, 255)",
                top: "7px",
                width: "50px",
                height: "30px",
              },
              textStyle: {
                fontSize: "15px"
              }
            },
            header_title:{
                type:"text",
                style:{
                  fontSize:14
                },
                text:"布局"
            },
            right_icon:{
                type:"icon",
                font:"icomoon_e90e",
                style:{
                    position:"absolute",
                    right:"10px",
                    color:"rgb(0, 147, 255)",
                    top:"6px",
                    width:"30px",
                    height:"30px",
                },
                iconStyle:{
                    fontSize:"20px"
                }
            },
            content_wrapper:{
              type:"view",
              style:{
                flex:1,
                overflowY:"auto",
                backgroundColor:"#fff"
              },
              root:["layout0_title","layout0","layout1_title","layout1","layout2_title","layout2","layout3_title","layout3","layout4_title","layout4","layout5_title","layout5","layout6_title","layout6","layout7_title","layout7","layout8_title","layout8"]
            },


            layout8_title:{
              type:"text",
              text:"水平布局居中垂直居下</br>(flexDirection:'row' , justifyContent:'center',alignItems:'flex-end')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout8:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"center",
                height:50,
                alignItems:'flex-end',
                backgroundColor:"#eee"
              },
              root:["layout8_view1","layout8_view2","layout8_view3"]
            },
            layout8_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout8_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout8_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },

            layout7_title:{
              type:"text",
              text:"水平布局居中垂直也居中</br>(flexDirection:'row' , justifyContent:'center',alignItems:'center')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout7:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"center",
                height:50,
                alignItems:'center',
                backgroundColor:"#eee"
              },
              root:["layout7_view1","layout7_view2","layout7_view3"]
            },
            layout7_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout7_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout7_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },

            layout6_title:{
              type:"text",
              text:"水平布局居space-around</br>(flexDirection:'row' , justifyContent:'space-around')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },

            layout6:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-around",
                height:50,
                backgroundColor:"#eee"
              },
              root:["layout6_view1","layout6_view2","layout6_view3"]
            },
            layout6_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout6_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout6_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },

            layout5_title:{
              type:"text",
              text:"水平布局居space-between</br>(flexDirection:'row' , justifyContent:'space-between')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },

            layout5:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"space-between",
                height:50,
                backgroundColor:"#eee"
              },
              root:["layout5_view1","layout5_view2","layout5_view3"]
            },
            layout5_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout5_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout5_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },


            layout4_title:{
              type:"text",
              text:"水平布局居右</br>(flexDirection:'row' , justifyContent:'flex-end')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },

            layout4:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"flex-end",
                height:50,
                backgroundColor:"#eee"
              },
              root:["layout4_view1","layout4_view2","layout4_view3"]
            },
            layout4_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout4_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout4_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },


            layout3_title:{
              type:"text",
              text:"水平布局居左</br>(flexDirection:'row' , justifyContent:'flex-start')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout3:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"flex-start",
                height:50,
                backgroundColor:"#eee"
              },
              root:["layout3_view1","layout3_view2","layout3_view3"]
            },
            layout3_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout3_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout3_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },

            layout2_title:{
              type:"text",
              text:"水平布局居中</br>(flexDirection:'row' , justifyContent:'center')",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:10,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout2:{
              type:"view",
              style:{
                flexDirection:"row",
                justifyContent:"center",
                height:50,
                backgroundColor:"#eee"
              },
              root:["layout2_view1","layout2_view2","layout2_view3"]
            },
            layout2_view1:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout2_view3:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },
            layout2_view2:{
              type:"view",
              style:{
                w:16,
                borderRadius:"50%",
                backgroundColor:"blue"
              }
            },

            layout1_title:{
              type:"text",
              text:"三列布局",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:5,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout1:{
              type:"view",
              style:{
                flexDirection:"row",
                height:50
              },
              root:["layout1_view1","layout1_view2","layout1_view3"]
            },
            layout1_view1:{
              type:"view",
              style:{
                width:50,
                backgroundColor:"red"
              }
            },
            layout1_view2:{
              type:"view",
              style:{
                flex:1,
                backgroundColor:"green"
              }
            },
            layout1_view3:{
              type:"view",
              style:{
                width:50,
                backgroundColor:"yellow"
              }
            },


            layout0_title:{
              type:"text",
              text:"三列均分",
              style:{
                color:"#333",
                fontSize:12,
                marginTop:5,
                marginBottom:5,
                paddingLeft:10
              }
            },
            layout0:{
              type:"view",
              style:{
                flexDirection:"row",
                height:50
              },
              root:["layout0_view1","layout0_view2","layout0_view3"]
            },
            layout0_view1:{
              type:"view",
              style:{
                flex:1,
                backgroundColor:"red"
              }
            },
            layout0_view2:{
              type:"view",
              style:{
                flex:1,
                backgroundColor:"green"
              }
            },
            layout0_view3:{
              type:"view",
              style:{
                flex:1,
                backgroundColor:"yellow"
              }
            }



          }

    };
});
