define(["../logic/ListViewDemo"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6"
        },
        root:["page2_header","pageContentView"],
        components:{
            page2_header:{
                type:"view",
                root:["backIcon","right_icon","header_title"],
                style:{
                    height:"44px",
                    borderBottom:"1px solid #e2e8ed",
                    backgroundColor:"#fff",
                    justifyContent:"center",
                    alignItems:"center"
                }
            },
            header_title:{
                type:"text",
                text:"ListView",
                style:{
                  fontSize:14
                }
            },
            right_icon:{
                type:"icon",
                font:"icomoon_e90e",
                style:{
                    position:"absolute",
                    right:"4px",
                    color:"rgb(0, 147, 255)",
                    top:"7px",
                    width:"30px",
                    height:"30px",
                },
                iconStyle:{
                  fontSize:"20px",
                }
            },
            backIcon:{
              type:"icon",
              text:"返回",
              style:{
                position: "absolute",
                left: "0px",
                color: "rgb(0, 147, 255)",
                top: "7px",
                width: "50px",
                height: "30px",
              },
              textStyle: {
                fontSize: "14px"
              }
            },
            pageContentView:{
                type:"view",
                root:["listview"],
                style:{
                  flex:1,
                  overflowY:"auto",
                  backgroundColor:"#fff"
                }
            },
            listview:{
              type:"listview",
              root:["row_topview","row_bottomview","row_splitline"],
              ajaxConfig:{
                url:"/getlistdata",
                type:"GET",
                pageSize:20,
                pageNumKey:"pageNum",
                data:{
                  pageSize:20
                }
              },
              style:{
                flexDirection:'column',
                paddingLeft:8,
              },
              rowStyle:{
                flexDirection:'column'
              },
              rowSwipeIcons:[]
            },
            rowDelIcon:{
              type:"icon",
              text:"删除",
              font:"icomoon_e903",
              textPos:"bottom",
              iconStyle:{
                fontSize:23,color:"#fff"
              },
              textStyle:{color:"#fff",fontSize:12,marginTop:2},
              style:{
                width:80,
                backgroundColor:"red",
              }
            },
            rowSwipeOtherIcon:{
              type:"icon",
              textStyle:{color:"#fff",fontSize:13},
              style:{
                width:90,
                backgroundColor:"#bbb"
              },
              text:"取消关注"
            },
            rowSetReadIcon:{
                type:"icon",
                textStyle:{color:"#fff",fontSize:13},
                style:{
                  width:90,
                  backgroundColor:"orange"
                },
                text:"设置为已读"
              },
            row_splitline:{
              type:"view",
              style:{
                borderTop:"1px solid #e2e8ed",
                marginTop:5,
                height:"0",
                transform:"scaleY(.5)"
              },
            },
            row_topview:{
              type:"view",
              style:{flexDirection:"row",
              paddingTop:9,
              paddingBottom:3},
              root:["row_title_status","row_state_wrapper"]
            },
            row_bottomview:{
              type:"view",
              style:{flexDirection:"row",
              paddingTop:5,
              paddingBottom:4},
              root:["row_time","row_person"]
            },
            row_time:{
              type:"text",
              text:"开始时间:2016-08-12",
              style:{
                fs:12,
                color:"#b0c0c7",
              }
            },
            row_person:{
              type:"text",
              text:"负责人:宋小宝",
              style:{
                fs:12,
                color:"#b0c0c7",
                marginLeft:10,
              }
            },
            row_state_wrapper:{
              type:"view",
              root:["row_state"],
              style:{
                width:70,
                alignItems:"flex-end"
              }
            },
            row_state:{
              type:"text",
              text:"已完成",
              style:{
                transform:"scale(.9)",
                marginRight:4,
                backgroundColor:"#b0c0c7",
                color:"#fff",
                textAlign:"center",
                fontSize:10,
                padding:"3px 10px",
                borderRadius:"14px"
              }
            },
            row_title_status:{
              type:"statusview",
              defaultKey:"row_title",
              style:{
                flex:1,
                alignItems: "center"
              }
            },
            row_title_icon:{
              type:"icon",
              font:"icomoon_e904",
              text:"sssssss",
              text_bind:"name",
              style:{
                flex:1,
                justifyContent:"flex-start"
              },
              textStyle:{
                fontSize:13,
                flex:1,
                color:"#292f33",
                marginLeft:3,
              },
              iconStyle:{
                fontSize:13,
                color:"orange",
              }
            },
            row_title:{
              type:"text",
              text:"sss",
              text_bind:"name",
              numberofline:1,
              style:{
                color:"#292f33",
                fontSize:13,
                flex:1,
              }
            }
        }
    };
});
