
define(["../logic/page1"],function(pluginClass){
    return {
        name:"",
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6"
        },
        root:["page1_header","viewpager","toppopover"],
        components:{

            toppopover:{
              type:"popover",
              root:["popover_repeat"],
              animate:{mode:"2"},
              style:{
                width:120,
                backgroundColor:"#fff",
                height:180
              },
              arrowStyle:{
                width:13,
                height:13,
                backgroundColor:"#fff",
              }
            },
            popover_repeat:{
              type:"repeat",
              items:[
                  {title:"多人聊天",icon:"icomoon_e903",color:"rgb(253,210,64)"},
                  {title:"加好友",icon:"icomoon_e904",color:"rgb(252,167,97)"},
                  {title:"扫一扫",icon:"icomoon_e905",color:"rgb(0,165,223)"},
                  {title:"面对面快传",icon:"icomoon_e906",color:"rgb(252,116,122)"},
                  {title:"付款",icon:"icomoon_e907",color:"rgb(13,184,246)"}
              ],
              root:["popover_icon"],
              style:{
                flexDirection:"column",
                flex:1,
              },
              itemStyle:{
                flexDirection:"row",
                flex:1,
                paddingLeft:10,
                alignItems:"center",
                justifyContent:"flex-start"
              },
              splitStyle:{
                borderTop:"1px solid rgb(214, 215, 216)",
                transform:"scaleY(.5)"
              }
            },
            popover_icon:{
              type:"icon",
              font:"icomoon_e91c",
              text_bind:"title",
              font_bind:"icon",
              iconStyle_bind:{
                color:"color"
              },
              text:"测试",
              textStyle:{
                fontSize:12,
                marginLeft:12,
                color:"#353535"
              },
              iconStyle:{
                fontSize:19
              }
            },
            page1_header:{
                type:"view",
                root:["header_lefticon","right_icon","header_segment"],
                style:{
                    height:"44px",
                    borderBottom:"1px solid #e2e8ed",
                    backgroundColor:"#fff",
                    justifyContent:"center",
                    alignItems:"center"
                }
            },
            header_lefticon:{
              type:"icon",
              font:"FontAwesome_f0c9",
              className:"",
              iconClassName:"",
              textClassName:"",
              style:{
                  position:"absolute",
                  left:"5px",
                  color:"rgb(0, 147, 255)",
                  top:"7px",
                  width:"30px",
                  height:"30px",
              },
              iconStyle:{
                  fontSize:"20px"
              }
            },
            header_text:{
                type:"text",
                text:"主页",
                style:{
                    fontSize:14,
                    width:"100px",
                    textAlign:"center"
                }
            },
            header_segment:{
              type:"segment_ios",
              items:[{title:"常规",icon:"icomoon_e907"},{title:"综合",icon:"icomoon_e904"}],
              root:["segment_ios_item2"],
              style:{height:23,width:120}
            },
            segment_ios_item2:{
              type:"icon",
              text:"test",
              text_bind:"title",
              selectedClassName:"yy-sgm-item-selected",
              textStyle:{color:"rgb(0, 147, 255)",fontSize:13,marginLeft:3},
            },
            right_icon:{
                type:"icon",
                font:"icomoon_e904",
                className:"",
                iconClassName:"",
                textClassName:"",
                style:{
                    position:"absolute",
                    right:"5px",
                    color:"rgb(0, 147, 255)",
                    top:"6px",
                    width:"30px",
                    height:"30px",
                },
                iconStyle:{
                    fontSize:"20px"
                }
            },
            viewpager:{
              type:"viewpager",
            defaultKey:"page1Repeat",
              style:{
                flex:1
              },
            },
            form_wrapper:{
              type:"view",
              root:["formsearchview","formrepeat"],
              style:{
                flex:1,
                backgroundColor:"#f2f3f4"
              }
            },
            repeat_wrapper:{
              type:"view",
              root:["searchview","repeat"],
              style:{
                flex:1,
                overflowY:"auto"
              }
            },
            formsearchview:{
              type:"view",
              style:{
                height:30,
                justifyContent:"center",
                alignItems:"center",
                backgroundColor:"#fff"
              },
              root:["formsearchinput"]
            },
            searchview:{
              type:"view",
              style:{
                height:30,
                justifyContent:"center",
                alignItems:"center",
                backgroundColor:"#fff"
              },
              root:["searchinput"]
            },
            searchinput:{
              type:"icon",
              style:{
                width:300,
                height:24,
                justifyContent:"center",
                alignItems:"center",
                backgroundColor:"rgb(238,239,243)",
                borderRadius:"5px"
              },
              textPos:"right",
              textStyle:{
                fontSize:12
              },
              iconStyle:{
                fontSize:14
              },
              text:"搜索",
              font:"icomoon_e90e"
            },
            formsearchinput:{
              type:"icon",
              style:{
                width:300,
                height:24,
                justifyContent:"center",
                alignItems:"center",
                backgroundColor:"rgb(238,239,243)",
                borderRadius:"5px"
              },
              textPos:"right",
              textStyle:{
                fontSize:12
              },
              iconStyle:{
                fontSize:14
              },
              text:"搜索",
              font:"icomoon_e90e"
            },
            formrepeat:{
              type:"repeat",
              root:["formrepeat_icon","formrepeat_righticon"],
              items:[
                  {title:"Form",icon:"icomoon_e903"},
                  {title:"TimePicker",icon:"icomoon_e903"},
                ],
              style:{
                backgroundColor:"#fff",
                flexDirection:"column"
              },
              itemStyle:{
                backgroundColor:"#fff",
                padding:"8px 0px",
                flexDirection:"row",
              },
              splitStyle:{
                  borderTop:"1px solid #e2e8ed",
                  marginLeft:"40px",
                  transform:"scaleY(.5)"
              },
            },
            formrepeat_icon:{
              type:"icon",
              font:"icomoon_e901",
              font_bind:"icon",
              text:"MenuItem",
              text_bind:"title",
              textStyle:{
                marginLeft:"5px",
                color:"#8899a6",
                fontSize:"14px"
              },
              textPos:"right",
              style:{
                flex:1,
                width:"130px",
                marginLeft:"7px",
                height:"30px",
                justifyContent:"flex-start"
              },
              iconStyle:{
                fontSize:"24px",
                color:"#8899a6"
              }
            },
            formrepeat_righticon:{
              type:"icon",
              iconStyle:{
                fontSize:14
              },
              style:{
                width:"30px",
                height:"30px"
              },
              font:"icomoon_e913"
            },
        }
    };
});/**
 * Created by xiaoz on 16/8/13.
 */
