/**
 * Created by xiaoz on 16/8/13.
 */
define(["../logic/page1Repeat"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f4f6",
            overflow:"auto"
        },
        root:["repeat"],
        components:{
            repeat:{
                type:"repeat",
                root:["repeat_icon","rp_right_icon"],
                items:[
                    {title:"新增页面示例",icon:"FontAwesome_f0f6"},
                    {title:"页面导航示例",icon:"FontAwesome_f0f6"},
                    {title:"布局",icon:"FontAwesome_f0f6"},
                    {title:"View",icon:"FontAwesome_f0f6"},
                    {title:"Text",icon:"FontAwesome_f0f6"},
                    {title:"Repeat",icon:"FontAwesome_f01e"},
                    {title:"Button",icon:"FontAwesome_f205"},
                    {title:"Icon",icon:"FontAwesome_f1b3"},
                    {title:"Image",icon:"FontAwesome_f1b3"},
                    {title:"ListView",icon:"FontAwesome_f039"},
                    {title:"Segment",icon:"FontAwesome_f085"},
                    {title:"ViewPager",icon:"FontAwesome_f076"},
                    {title:"Popover",icon:"icomoon_e900"},
                    {title:"PopLayer",icon:"icomoon_e900"},
                    {title:"Tabbar",icon:"FontAwesome_f1b3"},
                    // {title:"ConditionSelector",icon:"FontAwesome_f290"},
                    {title:"Calendar",icon:"FontAwesome_f073"}
                  ],
                style:{
                  backgroundColor:"#fff",
                  flexDirection:"column"
                },
                itemStyle:{
                  backgroundColor:"#fff",
                  padding:"8px 0px",
                  flexDirection:"row",
                },
                splitStyle:{
                    borderTop:"1px solid #e2e8ed",
                    marginLeft:"40px",
                    transform:"scaleY(.5)"
                },
            },
            rp_right_icon:{
              type:"icon",
              iconStyle:{
                fontSize:14
              },
              style:{
                width:"30px",
                height:"30px"
              },
              font:"icomoon_e913"
            },
            repeat_icon:{
              type:"icon",
              font:"icomoon_e901",
              font_bind:"icon",
              text:"MenuItem",
              text_bind:"title",
              textStyle:{
                marginLeft:"8px",
                color:"#8899a6",
                fontSize:"14px"
              },
              textPos:"right",
              style:{
                flex:1,
                width:"130px",
                marginLeft:"7px",
                height:"30px",
                justifyContent:"flex-start"
              },
              iconStyle:{
                fontSize:"22px",
                marginLeft:4,
                width:30,
                color:"#8899a6"
              }
            }
        }
    };
});/**
 * Created by xiaoz on 16/8/13.
 */
