define(["../logic/repeatentry"],function(pluginClass){
    return {
        pluginClass:pluginClass,
        style:{
            backgroundColor:"#f0f3f4"
        },
        root:["page_header","pageContentView"],
        components:{
            page_header:{
                type:"view",
                root:["backIcon","header_title"],
                style:{
                    height:"44px",
                    borderBottom:"1px solid #e2e8ed",
                    backgroundColor:"#fff",
                    justifyContent:"center",
                    alignItems:"center"
                }
            },
            header_title:{
                type:"text",
                text:"Repeat",
                style:{
                  fontSize:14
                }
            },
            backIcon:{
              type:"icon",
              text:"返回",
              style:{
                position: "absolute",
                left: "0px",
                color: "rgb(0, 147, 255)",
                top: "7px",
                width: "50px",
                height: "30px",
              },
              textStyle: {
                fontSize: "14px"
              }
            },
            pageContentView:{
                type:"view",
                root:["简单的九宫格","menu例子","工具栏","单选Repeat","多选Repeat"],
                style:{
                  flex:1,
                  overflowY:"auto"
                }
            },
            简单的九宫格:{
                type:"button",
                text:"简单的九宫格",
                style:{
                    marginTop:20,
                    width:"100%",
                    borderLeftWidth:0,
                    borderRightWidth:0,
                    borderRadius:0,
                    height:38,
                    borderColor:"#eee",
                    justifyContent:"center"
                },
            },
            menu例子:{
                type:"button",
                text:"menu例子",
                style:{
                    marginTop:20,
                    width:"100%",
                    borderLeftWidth:0,
                    borderRightWidth:0,
                    borderRadius:0,
                    height:38,
                    borderColor:"#eee",
                    justifyContent:"center"
                },
            },
            工具栏:{
                type:"button",
                text:"工具栏",
                style:{
                    marginTop:20,
                    width:"100%",
                    borderLeftWidth:0,
                    borderRightWidth:0,
                    borderRadius:0,
                    height:38,
                    borderColor:"#eee",
                    justifyContent:"center"
                },
            },
            单选Repeat:{
                type:"button",
                text:"单选Repeat",
                style:{
                    marginTop:20,
                    width:"100%",
                    borderLeftWidth:0,
                    borderRightWidth:0,
                    borderRadius:0,
                    height:38,
                    borderColor:"#eee",
                    justifyContent:"center"
                },
            },
            多选Repeat:{
                type:"button",
                text:"多选Repeat",
                style:{
                    marginTop:20,
                    width:"100%",
                    borderLeftWidth:0,
                    borderRightWidth:0,
                    borderRadius:0,
                    height:38,
                    borderColor:"#eee",
                    justifyContent:"center"
                },
            },
        }
    };
});
